#!/usr/bin/env bash
# Prints steps to finish Google Sign-In (cannot create OAuth clients without your Google login).
set -e
SLUG="autoswipe-native"
BUNDLE="com.autoswipe.native"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo ""
echo "=== Google OAuth — paste Client IDs into .env ==="
echo ""
echo "1) Open: https://console.cloud.google.com/apis/credentials"
echo "   (pick or create a project; enable Google+ API / People API if asked)"
echo ""
echo "2) OAuth consent screen: External, add your email as test user if in Testing."
echo ""
echo "3) Create credentials → OAuth client → Web application"
echo "   Name: AutoSwipe Expo Web"
echo "   Authorized JavaScript origins (add all that apply):"
echo "     http://localhost:8081"
echo "     http://localhost:19006"
echo "   Authorized redirect URIs — for Expo Go / dev, add the proxy redirect:"
echo "     https://auth.expo.io/@YOUR_EXPO_USERNAME/${SLUG}"
echo "   (Replace YOUR_EXPO_USERNAME with your Expo account username from expo.dev)"
echo "   Dev builds: also allow the custom scheme from app.config (autoswipe + com.googleusercontent.apps.*)"
echo ""
echo "4) Create credentials → OAuth client → iOS"
echo "   Bundle ID: ${BUNDLE}"
echo ""
echo "5) Copy IDs into files (same Web ID in both places for server mirror):"
echo "   ${ROOT}/.env"
echo "     EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=....apps.googleusercontent.com"
echo "     EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=....apps.googleusercontent.com"
echo "   ../autoswipe/.env"
echo "     GOOGLE_CLIENT_ID=\"web-id.apps.googleusercontent.com,ios-id.apps.googleusercontent.com\""
echo "     (or set GOOGLE_IOS_CLIENT_ID separately — API merges them)"
echo ""
echo "6) Restart: Metro (expo start) and Next (npm run dev)."
echo ""
